project:
  type: book
  output-dir: docs

book:
  title: "Trajectory-based Operational Performance Assessment"
  subtitle: "(initial) Vertical Flight Efficiency"
  author: "PBWG"
#  date: ""
  chapters:
    - index.qmd
    - 10_introduction.qmd
#   - intro.qmd
    - 80_conclusions.qmd
    - 90_data-preparation.qmd
    - 99_references.qmd
  repo-url: https://github.com/euctrl-pru/pbwgtrajectory
  downloads: [pdf, docx]

# check blog and how to install
# https://albert-rapp.de/posts/13_quarto_blog_writing_guide/13_quarto_blog_writing_guide.html
# https://github.com/apps/utterances/installations/select_target
# requires separate repo ... adds comment field at bottom


bibliography: references.bib

format:
  html:
    theme: cosmo
    comments:
      utterances:
        repo: euctrl-pru/pbwgtrajectory
  pdf:
    documentclass: scrreport
  docx: default
#  epub:
#    cover-image: cover.png