project:
  type: book
  output-dir: docs

book:
  title: "Trajectory-based Operational Performance Assessment"
  subtitle: "(initial) Vertical Flight Efficiency"
  author: "PBWG"
#  date: ""
  chapters:
    - index.qmd
    - 10_introduction.qmd
#   - intro.qmd
    - 80_conclusions.qmd
    - 90_data-preparation.qmd
    - 99_references.qmd
  repo-url: https://github.com/euctrl-pru/pbwgtrajectory
  downloads: [pdf, docx]

comments:
  utterances:
    repo: ttps://github.com/euctrl-pru/pbwgtrajectory

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreport
  docx: default
#  epub:
#    cover-image: cover.png